Listen2nite/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', home, name='home'),
    path('', include('user.urls')),
    path('', include('userdetail.urls')),
    path('', include('topic.urls')),
]

user/urls.py
from django.urls import include, path
from django.contrib.auth import views as auth_views

from .views import check_code, UserSignUpView, UserLoginView

app_name = 'user'

urlpatterns = [
    path('user/', include(([
        # path('login/', auth_views.LoginView.as_view(template_name='user/login.html'), name='login'),
        path('signup/', UserSignUpView.as_view(), name='signup'),
        path('login/', UserLoginView.as_view(), name='login'),
        path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    ]))),
    path('checkcode/', check_code, name='checkcode'),
]

user/models.py
from datetime import datetime

from django.db import models
from django.contrib.auth.models import AbstractUser


class UserProfile(AbstractUser):
    """
    用户表
    """
    GENDER_TYPE = (
        ('male', '男'),
        ('female', '女'),
        ('secret', '保密'),
    )

    STATUS_TYPE = (
        ('ONLINE', '在线'),
        ('OFFLINE', '离线'),
    )

    VERIFY_STATUS = (
        (0, '未验证'),
        (1, '已验证'),
    )
    birthday = models.DateField(null=True, blank=True, verbose_name='出生日期')
    gender = models.CharField(max_length=6, choices=GENDER_TYPE, default='secret', verbose_name='性别')
    location = models.CharField(max_length=30, null=True, blank=True, default="", verbose_name="所在城市")
    mobile = models.CharField(max_length=11, null=True, blank=True, default="", verbose_name="电话")
    email = models.CharField(max_length=100, null=True, blank=True, default="", verbose_name="邮箱")
    email_verify = models.IntegerField(choices=VERIFY_STATUS, default=0, verbose_name="Email是否已经验证")
    mobile_verify = models.IntegerField(choices=VERIFY_STATUS, default=0, verbose_name="Mobile是否已经验证")
    avatar = models.CharField(max_length=50, null=True, blank=True, default="/static/img/default-avatar.png",
                              verbose_name="头像")
    session = models.CharField(max_length=50, null=True, blank=True, default="",
                               verbose_name="用户登录时会写入当前session_key")
    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")
    update_time = models.DateTimeField(auto_now=True, verbose_name="更新时间")

    class Meta:
        verbose_name = "用户"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.username


class VerifyCode(models.Model):
    """
    邮箱和手机验证码
    """
    VERIFY_CODE_TYPE = (
        (0, 'Email'),
        (1, 'Mobile')
    )
    code = models.CharField(max_length=10, verbose_name="验证码")
    to = models.CharField(max_length=30, verbose_name="发送给谁")
    code_type = models.IntegerField(choices=VERIFY_CODE_TYPE, default=0, verbose_name="验证码类型")
    task_id = models.CharField(max_length=37, null=True, blank=True, verbose_name="任务的返回id")
    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")
    update_time = models.DateTimeField(auto_now=True, verbose_name="更新时间")

    class Meta:
        verbose_name = '邮箱和手机验证码'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.to


# class UserFollowing(models.Model):
#     """
#     用户的Following 和 Block 关系表
#     """
#     CHOICES = (
#         (-1, "None"),
#         (0, "False"),
#         (1, "True"),
#     )
#
#     user = models.ForeignKey(UserProfile, verbose_name="用户", on_delete=models.CASCADE, related_name="follower")
#     following = models.ForeignKey(UserProfile, verbose_name="关注那个用户", on_delete=models.CASCADE,
#                                   related_name="following")
#     is_following = models.IntegerField(choices=CHOICES, default=CHOICES[0][0], verbose_name="是否Following")
#     is_block = models.IntegerField(choices=CHOICES, default=CHOICES[0][0], verbose_name="是否Block")
#     add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")
#     update_time = models.DateTimeField(auto_now=True, verbose_name="更新时间")
#
#     class Meta:
#         verbose_name = "用户的Following 和 Block 关系表"
#         verbose_name_plural = verbose_name
#         unique_together = ('user', 'following',)
#
#     def __str__(self):
#         return self.user.username
#
#     # 计算关注人数总数
#     def count_following(self):
#         return UserFollowing.objects.filter(user=self, is_following=1).count()
#
#     # 计算被关注数量
#     def count_follower(self):
#         return UserFollowing.objects.filter(following=self, is_following=1).count()

user/forms.py
import re

from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import AuthenticationForm

from .models import UserProfile


def mobile_validate(value):
    mobile_re = re.compile(r'^(13[0-9]|15[012356789]|17[678]|18[0-9]|14[57])[0-9]{8}')
    if not mobile_re.match(value):
        raise ValidationError("手机号码格式错误")


def user_unique_validate(username):
    user_obj = UserProfile.objects.filter(username=username).first()
    if user_obj:
        raise ValidationError("此用户名已存在, 请换一个")


def username_rule_validate(value):
    # 先设定一个正则，非 [a-z][0-9]
    username_re = re.compile(r'\W|[A-Z]')
    # 判断如果查找所有的数据后有正则中的指定的字符串
    if username_re.findall(value):
        # 说明匹配，但是匹配就是非[a-z][0-9]  而我们想要的是[a-z][0-9]
        raise ValidationError('用户名格式错误 只能在[a-z][0-9]中选择')
    # 不匹配，说明 value 全在 [a-z][0-9] 这个范围里


def email_unique_validate(email):
    user_obj = UserProfile.objects.filter(email=email).first()
    if user_obj:
        raise ValidationError('Email已经存在，请换一个')


class SignupForm(forms.ModelForm):
    username = forms.CharField(validators=[user_unique_validate, username_rule_validate, ],
                               required=True,
                               max_length=30, min_length=5,
                               error_messages={'required': '用户名不能为空',
                                               'max_length': '用户名至少5位',
                                               'min_length': '用户名最多30位'})
    password = forms.CharField(min_length=6, max_length=50, required=True,
                               widget=forms.PasswordInput(),
                               error_messages={'required': '密码不能为空',
                                               'invalid': '密码格式错误',
                                               'min_length': '密码不能少于6位',
                                               'max_length': '密码最多50位'})
    email = forms.EmailField(validators=[email_unique_validate, ], required=True,
                             error_messages={'required': '邮箱不能为空',
                                             'invalid': '邮箱格式错误'})
    mobile = forms.CharField(validators=[mobile_validate, ], required=True,
                             error_messages={'required': '手机号不能为空'})
    # checkcode = forms.CharField(min_length=4, max_length=10, required=True,
    #                             error_messages={'required': '验证码不能为空',
    #                                             'invalid': '验证码不匹配'})

    class Meta:
        model = UserProfile
        # fields = ['username', 'password', 'email', 'mobile', 'checkcode']
        fields = ['username', 'password', 'email', 'mobile']


class LoginForm(forms.ModelForm):
    # username = forms.CharField(required=True, max_length=50,
    #                            error_messages={'required': '用户名不能为空'}, )
    username = forms.CharField(required=True, max_length=50,
                               error_messages={'required': '用户名不能为空'}, )
    password = forms.CharField(min_length=6, max_length=50, required=True,
                               widget=forms.PasswordInput(),
                               error_messages={'required': '密码不能为空',
                                               'invalid': '密码格式错误',
                                               'min_length': '密码不能少于6位'})
    # checkcode = forms.CharField(min_length=4, max_length=10, required=True,
    #                             error_messages={'required': '验证码不能为空',
    #                                             'invalid': '验证码不匹配'})

    class Meta:
        model = UserProfile
        fields = ['username', 'password']

# class LoginForm(AuthenticationForm)

user/views.py
from io import BytesIO
from datetime import datetime

from django.shortcuts import render, HttpResponse, redirect
from django.contrib.auth import login
from django.urls import reverse
from django.core.cache import cache
from django.http import Http404
from django.db.models import Q
from django.views.generic import (
    CreateView, View
)
from django.views.generic.edit import FormView, ProcessFormView
from django.contrib.auth.views import LoginView
from django.db.models import Q
from django.contrib.auth.forms import AuthenticationForm

from .models import UserProfile
from .forms import SignupForm, LoginForm
from utils.captcha import create_validate_code


def check_code(request):
    """
    验证码
    :param request:
    :return:
    """
    stream = BytesIO()
    img, code = create_validate_code()
    img.save(stream, 'PNG')
    request.session['CheckCode'] = code
    return HttpResponse(stream.getvalue())


class UserSignUpView(CreateView):
    """
    注册视图
    """
    model = UserProfile
    form_class = SignupForm
    template_name = 'user/signup.html'

    def form_valid(self, form):
        # 比较验证码
        # 存入数据库
        # print(self.request.session['CheckCode'])
        # print(self.request.POST.get('check_code'))
        if self.request.session['CheckCode'].upper() == self.request.POST.get('check_code').upper():
            # print('验证码相同')
            user = form.save()
            # print('验证成功')
            login(self.request, user)
            return redirect('home')
        else:
            return redirect('user:signup')


class UserLoginView(FormView):
    """
    注册视图
    """
    model = UserProfile
    form_class = LoginForm
    template_name = 'user/login.html'

    # def post(self, request, *args, **kwargs):
    #     form = self.get_form()
    #     return self.form_valid(form)

    def form_valid(self, form):
        # 比较验证码
        # 存入数据库
        print(self.request.session['CheckCode'])
        print(self.request.POST.get('check_code'))
        if self.request.session['CheckCode'].upper() == self.request.POST.get('check_code').upper():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = UserProfile.objects.filter(Q(username=username) | Q(password=password))
            login(self.request, user)
            return redirect('topic:index')
        else:
            return redirect('user:login')

    def form_invalid(self, form):
        print('无效输入')
        print(form)
        print(self.request.session['CheckCode'])
        print(self.request.POST.get('check_code'))
        if self.request.session['CheckCode'].upper() == self.request.POST.get('check_code').upper():
            username = self.request.POST.get('username')
            password = self.request.POST.get('password')
            user = UserProfile.objects.filter(Q(username=username) | Q(password=password)).first()
            login(self.request, user)
            return redirect('topic:index')
        else:
            return redirect('user:login')

user/templates/user/login.html
{% extends 'user/master.html' %}
{% load staticfiles %}


{% block main %}
    <div class="box">
        <div class="header"><a href="/">Listen2nite</a><span class="chevron"> > </span> 登录 </div>
        {% if has_error %}
            <div class="problem">请解决以下问题后再提交:
                <ul>
                    {% if obj.errors.username.0 %}
                        <li>{{ obj.errors.username.0 }}</li>
                    {% endif %}
                    {% if obj.errors.password.0 %}
                        <li>{{ obj.errors.password.0 }}</li>
                    {% endif %}
                    {% if user_error %}
                        <li>{{ user_error }}</li>
                    {% endif %}
                    {% if code_error %}
                        <li>{{ code_error }}</li>
                    {% endif %}
                </ul>
            </div>
        {% endif %}
        <div class="inner">
            <form method="post" action="{% url 'user:login' %}" novalidate>
                {% csrf_token %}
                <table cellpadding="5" cellspacing="0" border="0" width="100%">
{#                    {% if next_url %}#}
{#                        <input type="hidden" name="next" value="{{ next_url }}">#}
{#                    {% endif %}#}
                    <tbody>
                        <tr>
                            <td width="120" align="right" valign="top">
                                <div class="sep5"></div>
                                用户名
                            </td>
                            <td width="auto" align="left">
                                {{ form.username }}
                                <div class="sep5"></div>
                            </td>
                        </tr>
                        <tr>
                            <td width="120" align="right">密码</td>
                            <td width="auto" align="left">
                                {{ form.password }}
                            </td>
                        </tr>
                        <tr>
                            <td width="120" align="right">你是机器人么?</td>
                            <td width="auto" align="left">
                                <img src="{% url 'user:checkcode' %}" id="checkCode" style="width: 120px; height: 35px; border-radius: 3px; border: 1px solid #ccc;"/>
                                <div class="sep10"></div>
                                <input type="text" class="sls" name="check_code" value="" placeholder="请输入上图中的验证码">
                            </td>
                        </tr>
                        <tr>
                            <td width="120" align="right"></td>
                            <td width="auto" align="left">
                                <input type="submit" class="btn btn-sm btn-secondary" value="登录">
                            </td>
                        </tr>
{#                        <tr>#}
{#                            <td width="120" align="right"></td>#}
{#                            <td width="auto" align="left">#}
{#                                <a href="#">我忘记密码了</a>#}
{#                            </td>#}
{#                        </tr>#}
                    </tbody>
                </table>
            </form>
        </div>
    </div>
{% endblock %}

{% block rightbar %}
    <div class="box">
        <div class="cell">
            <strong>你也可以选择以下方式登录</strong>
        </div>
        <div class="inner">
            <div class="sep5"></div>
                <div align="center"><a href="{% url 'user:signup' %}" class="btn btn-sm btn-secondary">现在注册</a>
                    <div class="sep5"></div>
                    <div class="sep10"></div>
                    已注册用户请 &nbsp;<a href="{% url 'user:login' %}">登录</a></div>
        </div>
    </div>
{#    <div class="sep20"></div>#}
{#    <div class="box">#}
{#        <div class="inner"></div>#}
{#    </div>#}
    <div class="sep20"></div>
{% endblock %}

{% block JS %}
    <script>
        $("#checkCode").click(function () {
            this.src += '?'
        });
    </script>
{% endblock %}

user/templates/user/master.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load static %}

{% block CSS %}
    <link rel="stylesheet" href="{% static 'css/user.css' %}">
{% endblock %}


{% block rightbar %}
    {% if request.session.user_info %}
        <div class="box">
            <div class="cell">
                <table cellpadding="0" cellspacing="0" border="0" width="100%">
                    <tbody>
                    <tr>
                        <td width="48" valign="top"><a href="#"><img
                                src="{{ request.session.user_info.avatar }}"
                                class="rounded" border="0" align="default"
                                style="max-width: 48px; max-height: 48px;"></a></td>
                        <td width="10" valign="top"></td>
                        <td width="auto" align="left"><span class="bigger"><a
                                href="#"></a></span>
                        </td>
                    </tr>
                    </tbody>
                </table>
                <div class="sep10"></div>
                <table cellpadding="0" cellspacing="0" border="0" width="100%">
                    <tbody>
                    <tr class="no_hove_line">
                        <td width="33%" align="center"><a href="#" class="dark" style="display: block;"><span
                                class="bigger">{{ request.session.user_info.favorite_node_num }}</span>
                            <div class="sep3"></div>
                            <span>节点收藏</span></a></td>
                        <td width="34%"
                            style="border-left: 1px solid rgba(100, 100, 100, 0.4); border-right: 1px solid rgba(100, 100, 100, 0.4);"
                            align="center"><a href="#" class="dark" style="display: block;"><span
                                class="bigger">{{ request.session.user_info.favorite_topic_num }}</span>
                            <div class="sep3"></div>
                            <span>主题收藏</span></a></td>
                        <td width="33%" align="center"><a href="#" class="dark"
                                                          style="display: block;"><span class="bigger">{{ request.session.user_info.following_user_num }}</span>
                            <div class="sep3"></div>
                            <span>特别关注</span></a></td>
                    </tr>
                    </tbody>
                </table>
            </div>
            <div class="cell">
                <div style="width: 250px; background-color: #f0f0f0; height: 3px; display: inline-block; vertical-align: middle;">
                    <div style="width: 40px; background-color: #ccc; height: 3px; display: inline-block;"></div>
                </div>
            </div>
            <div class="cell" style="padding: 5px;">
                <table cellpadding="0" cellspacing="0" border="0" width="100%">
                    <tbody>
                    <tr>
                        <td width="32"><a href="#"><img
                                src="/static/img/flat_compose.png" width="32"
                                border="0"></a></td>
                        <td width="10"></td>
                        <td width="auto" valign="middle" align="left"><a href="#">创作新主题</a></td>
                    </tr>
                    </tbody>
                </table>
            </div>
            <div class="inner">
                {% if request.session.user_info.show_balance == 1 %}
                    <div class="fr" id="money">
                        <a href="#" class="badge badge-pill badge-light">

                            <img src="/static/img/bronze.png" border="0">
                        </a>
                    </div>
                {% endif %}
                <a href="/notifications">0 条未读提醒</a></div>
        </div>
        <div class="sep20"></div>
        <div class="box">
            <div class="inner">
                {% if not request.session.user_info.daily_mission %}
                    <li class="fa fa-gift" style="color: #f90;"></li> &nbsp;<a href="#">领取今日的登录奖励</a>
                {% endif %}
            </div>
        </div>
        <div class="sep20"></div>
    {% else %}
        <div class="box">
            <div class="cell">
                <strong>V2EX = way to explore</strong>
{#                <div class="sep5"></div>#}
{#                <span>V2EX 是一个关于分享和探索的地方</span>#}
            </div>
            <div class="inner">
                <div class="sep5"></div>
                <div align="center"><a href="{% url 'user:signup' %}" class="btn btn-sm btn-secondary">现在注册</a>
                    <div class="sep5"></div>
                    <div class="sep10"></div>
                    已注册用户请 &nbsp;<a href="{% url 'user:login' %}">登录</a></div>
            </div>
        </div>
{#        <div class="sep20"></div>#}
{#        <div class="box">#}
{#            <div class="inner">#}
{#            </div>#}
{#        </div>#}
        <div class="sep20"></div>
    {% endif %}
{% endblock %}

user/templates/user/signup.html
{% extends 'user/master.html' %}
{#{% load staticfiles %}#}

{#{% block CSS %}#}
{#    <link rel="stylesheet" href="{% static 'css/user.css' %}"/>#}
{#{% endblock %}#}


{% block main %}
    <div class="box">
        <div class="header"><a href="/">Listen2nite</a><span class="chevron"> > </span> 注册 </div>
        {% if has_error %}
            <div class="problem">请解决以下问题后再提交:
                <ul>
                    {% if obj.errors.username.0 %}
                        <li>{{ obj.errors.username.0 }}</li>
                    {% endif %}
                    {% if obj.errors.password.0 %}
                        <li>{{ obj.errors.password.0 }}</li>
                    {% endif %}
                    {% if obj.errors.email.0 %}
                        <li>{{ obj.errors.email.0 }}</li>
                    {% endif %}
                    {% if obj.errors.mobile.0 %}
                        <li>{{ obj.errors.mobile.0 }}</li>
                    {% endif %}
                    {% if code_error %}
                        <li>{{ code_error }}</li>
                    {% endif %}
                </ul>
            </div>
        {% endif %}
        <div class="inner">
            <form method="post" action="{% url 'user:signup' %}" novalidate>
                {% csrf_token %}
                <table cellpadding="5" cellspacing="0" border="0" width="100%">
                    <tbody>
                        <tr>
                            <td width="120" align="right" valign="top">
                                <div class="sep5"></div>
                                用户名
                            </td>
                            <td width="auto" align="left">
{#                                <div class="sep5"></div>#}
                                {{ form.username }}
                                <div class="sep5"></div>
                                <span class="comment">请使用英文字母 a-z,A-Z 或数字 0-9 </span>
                            </td>
                        </tr>
                        <tr>
                            <td width="120" align="right">密码</td>
                            <td width="auto" align="left">
                                {{ form.password }}
                            </td>
                        </tr>
                        <tr>
                            <td width="120" align="right" valign="top">
                                <div class="sep5"></div>
                                电子邮件
                            </td>
                            <td width="auto" align="left">
                                {{ form.email }}
                                <div class="sep5"></div>
                                <span class="comment">请使用真实电子邮箱注册，我们不会将你的邮箱地址分享给任何人</span>
                            </td>
                        </tr>
                        <tr>
                            <td width="120" align="right" valign="top">
                                <div class="sep5"></div>
                                手机号码
                            </td>
                            <td width="auto" align="left">
                                {{ form.mobile }}
                                <div class="sep5"></div>
                            </td>
                        </tr>
                        <tr>
                            <td width="120" align="right">你是机器人么?</td>
                            <td width="auto" align="left">
                                <img src="{% url 'user:checkcode' %}" id="checkCode" style="width: 120px; height: 35px; border-radius: 3px; border: 1px solid #ccc;">
                                <div class="sep10"></div>
                                <input type="text" class="sls" name="check_code" value="" placeholder="请输入上图中的验证码"></td>
                            </td>
                        </tr>
                        <tr>
                            <td width="120" align="right"></td>
                            <td width="auto" align="left">
                                <input type="submit" class="btn btn-sm btn-secondary" value="注册">
                            </td>
                        </tr>
                    </tbody>
                </table>
            </form>
        </div>
    </div>
{% endblock %}

{% block JS %}
    <script>
        $("#checkCode").click(function () {
            this.src += '?'
        });
    </script>
{% endblock %}