Listen2nite/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', home, name='home'),
    path('', include('user.urls')),
    path('', include('userdetail.urls')),
    path('', include('topic.urls')),
]

user/urls.py
from django.urls import include, path
from django.contrib.auth import views as auth_views

from .views import check_code, UserSignUpView, UserLoginView

app_name = 'user'

urlpatterns = [
    path('user/', include(([
        # path('login/', auth_views.LoginView.as_view(template_name='user/login.html'), name='login'),
        path('signup/', UserSignUpView.as_view(), name='signup'),
        path('login/', UserLoginView.as_view(), name='login'),
        path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    ]))),
    path('checkcode/', check_code, name='checkcode'),
]

userdetail/urls.py
from django.urls import include, path
from django.contrib.auth import views as auth_views

from .views import SettingsView


app_name = 'userdetail'


urlpatterns = [
    path('userdetail/', include(([
        path('settings/', SettingsView.as_view(), name='settings'),
    ]))),
]

templates/base.html
{#{% load staticfiles %}#}
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <title>Listen2nite</title>
    <link rel="stylesheet" href="/static/css/bootstrap.css">
    <link rel="stylesheet" href="/static/css/font-awesome.css">
    <link rel="stylesheet" href="/static/plugin/highlight/tomorrow.css">
    <link rel="stylesheet" href="/static/css/base.css">
    {% block CSS %} {% endblock %}
</head>
<body>
<div id="Top">
    <div class="content">
        <div style="padding-top: 6px;">
            <table cellpadding="0" cellspacing="0" border="0" width="100%">
                <tbody>
                <tr>
                    <td width="110" align="left"><a href="/" name="top" title="way to explore"><img
                            src="/static/img/fake_logo@2x.png" border="0" align="default" alt="V2EX"
                            width="94" height="30"></a></td>
                    <td width="auto" align="left">
                        <div id="Search">
                            <form action="https://www.google.com" onsubmit="return dispatch()" target="_blank">
                                <div style="width: 276px; height: 28px; background-size: 276px 28px; background-image: url('/static/img/qbar_light@2x.png'); background-repeat: no-repeat; display: inline-block;">
                                    <input type="text" maxlength="40" name="q" id="q" value=""/>
                                </div>
                            </form>
                        </div>
                    </td>
                    {% if not user.is_anonymous %}
                        <td width="570" align="right" style="padding-top: 2px;">
                            <a href="/" class="top">首页</a>
                            <a href="#" class="top">{{ user.username }}</a>
{#                            <a href="/notes" class="top">记事本</a>#}
                            <a href="{% url 'userdetail:settings' %}" class="top">设置</a>
                            <a href="#;" onclick="if (confirm('确定要从 Listen2nite 登出？')) { location.href= '{% url 'user:logout' %}'; }" class="top">登出</a>
                        </td>
{#                            <a href="{% url 'user:logout' %}" class="top">登出</a>#}
                    {% else %}
                            <td width="570" align="right" style="padding-top: 2px;">
                                <a href="/" class="top">首页</a>
                                <a href="{% url 'user:signup' %}" class="top">注册</a>&nbsp;&nbsp;
                                <a href="{% url 'user:login' %}" class="top">登录</a>
                            </td>
                    {% endif %}
                </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

<div id="Wrapper">
    <div class="content">
        <div id="Leftbar"></div>
        <div id="Rightbar">
            <div class="sep20"></div>
            {% block rightbar %} {% endblock %}
        </div>
        <div id="Main">
            <div class="sep20"></div>
            {% block main %}
            {% endblock %}
        </div>
        <div class="sep20"></div>
    </div>
    <div class="c"></div>
    {% if is_login %}
        {% csrf_token %}
    {% endif %}

<div id="Bottom">
    <div class="content">
        <div class="inner">
            <div class="sep10"></div>
            <strong><a href="/about" class="dark" target="_self">关于</a> &nbsp; <span class="snow">·</span> &nbsp; <a
                    href="/faq" class="dark" target="_self">FAQ</a> &nbsp; <span class="snow">·</span> &nbsp; <a
                    href="/p/7v9TEc53" class="dark" target="_self">API</a> &nbsp; <span class="snow">·</span> &nbsp; <a
                    href="/mission" class="dark" target="_self">我们的愿景</a> &nbsp; <span class="snow">·</span> &nbsp; <a
                    href="/advertise" class="dark" target="_self">广告投放</a> &nbsp; <span class="snow">·</span> &nbsp; <a
                    href="/advertise/2016.html" class="dark" target="_self">鸣谢</a> &nbsp; <span class="snow">·</span>
                    &nbsp; {{ request.online_member_count }} 人在线</strong>&nbsp;<span
                    class="snow">·</span> &nbsp; <span>您的IP是: {{ request.current_visitor_ip }}</span></a>
            <div class="sep20"></div>
            创意工作者们的社区
            <div class="sep5"></div>
            World is powered by solitude
            <div class="sep20"></div>
            <div class="sep10"></div>
        </div>
    </div>
    {% block footer %} {% endblock %}
</div>
</div>


<script src="/static/js/jquery-3.3.1.js"></script>
<script src="/static/js/jquery.cookie.js"></script>
<script src="/static/js/bootstrap.js"></script>
<script src="/static/plugin/highlight/highlight.pack.js"></script>

<script>
    /* Ajax 初始化请求操作*/
    $(function () {
        $.ajaxSetup({
            beforeSend: function (xhr, settings) {
                xhr.setRequestHeader('X-CSRFtoken', $.cookie('csrftoken'));
            }
        });
    });
    /* title 变化 */
    document.addEventListener("visibilitychange", function () {
        if (document.hidden) {
            $('title').text('Listen2nite');
        } else {
            $('title').text('欢迎回来ヽ(✿ﾟ▽ﾟ)ノ');
            setTimeout("$('title').text('V2EX');", 3000);
        }
    }, false);

</script>
<script>hljs.initHighlightingOnLoad();</script>
{% block JS %} {% endblock %}
</body>
</html>